version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mentorixer
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
